**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [26]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [27]:
#Code here
print((np.arange(10) == 4).astype(int))
print( (np.arange(10) ==4).view(np.uint8))
print( np.where(np.arange(10)==4,1,0) )
print( np.array([int(x==4) for x in range(10)]) )

[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [28]:
#Code here
a = int(input('Enter number of rows :- '))
b = int(input('Enter number of columsn :- '))
arr = np.random.random((a,b))
print('Array is :- \n ',arr)
print('Aveerage of array :- ',np.average(arr))

Array is :- 
  [[0.42501496 0.02521345 0.72471857]
 [0.99544505 0.45134878 0.39201958]]
Aveerage of array :-  0.5022934007498272


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [29]:
#Code here
def create_array(a,b):
    r_indices,c_indices = np.indices((a,b))
    a1 = np.where( (r_indices==0) | (c_indices==0) | (r_indices==(a-1)) | (c_indices == (b-1)),1,0 )
    return a1
a = int(input('Enter number of rows :- '))
b = int(input('Enter number of columsn :- '))
print(create_array(a,b))

[[1 1 1]
 [1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [30]:
#Code here
a1 = np.linspace(0,1,11,endpoint=False)[1:]
a1

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.
- No, you cannot create a true identity matrix of shape (3,4) because by definition, an identity matrix must be a square matrix (having an equal number of rows and columns).However, you can create a rectangular matrix with ones on the main diagonal and zeros elsewhere (often referred to as a "2D identity-like array" or a matrix with a unit diagonal)

In [31]:
#Code here
print(np.eye(3,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [32]:
#Code here
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [33]:
#code here
a1 = np.random.randint(1,100,20).reshape(10,2)
pt = np.array([2,3])

def dist(a1):
    dist = []
    dist.append([  np.abs(( (a1[0]-pt[0])**2 + (a1[1]-pt[1]**2 ) )**0.5) ])
    return dist
print(dist(a1))

[[array([65.22269544, 90.35485598])]]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
#Code here
a1 = np.arange(336).reshape(6,7,8)
a1[1,5,4]

np.int64(100)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [35]:
#Code here
lst = [1,2,3,4,-8,-10]
a1 = np.array(lst)[::-1].astype(np.float64)
print(a1)

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [39]:
#Code here

import numpy
user_input = input('Enter array elements seperated by spaces')
a1 = np.array(user_input.split(),dtype=int)
print(a1.size)

3


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [45]:
#Code here
# softmax has a numerator part and a denominator part
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x/e_x.sum(axis=0)
scores = [86.03331084, 37.7285648 , 48.64908087, 87.16563062, 38.40852563, 37.20006318]
print(softmax(scores))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [46]:
#Coder here
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
c = np.array([[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

output = np.vstack((a,b,c))
print(output)


[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [49]:
import numpy as np

# Define your start and end dates (YYYY-MM-DD)
# Note: The end date is exclusive by default in np.arange
start_date = '2026-06-01'
end_date = '2026-06-10'

# Generate all dates in between
dates = np.arange(start_date, end_date, dtype='datetime64[D]')

# Print the resulting array
print(dates)


['2026-06-01' '2026-06-02' '2026-06-03' '2026-06-04' '2026-06-05'
 '2026-06-06' '2026-06-07' '2026-06-08' '2026-06-09']


###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2761, 7436, 4246, 9810, 3506],
       [2967, 1642, 9786, 1470, 5885],
       [8324, 6462, 1531, 3063, 6124],
       [6103, 8447, 2666, 5793, 2352],
       [7699, 1138, 9832, 7137, 1498],
       [9369, 9440, 6604, 7922, 8536],
       [ 941, 1078, 2710, 7409, 6796],
       [1726, 2835, 9524, 6229, 7594]], dtype=int32)

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here